server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: base-service
        uri: lb://base-service
        predicates:
        - Path=/base/**
        filters:
        - RewritePath=/base/(?<path>.*), /$\{path}
      - id: storage-service
        uri: lb://storage-service
        predicates:
        - Path=/storage/**
        filters:
        - RewritePath=/storage/(?<path>.*), /$\{path}
        
zuul:
  routes:
    base:
      path: /base/**
      serviceId: base-service
    storage:
      path: /storage/**
      serviceId: storage-service